name: Deploy to GitHub Pages

on:
  push:
    branches: [ dev ]

permissions:
  contents: write 
  pages: write
  id-token: write

jobs:
# Test
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          cd food-app
          npm install
      - name: Run tests
        run: |
          cd food-app
          npm run test

# Build and Deploy
  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout dự án
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Cài đặt NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './food-app/package-lock.json'
    
    - name: Cài đặt các dependencies
      run: |
        cd food-app
        npm install
    
    - name: Build for GitHub Pages
      run: |
        cd food-app
        npm run build
      env:
        NODE_ENV: production
        GITHUB_PAGES: true
    
    - name: Deploy to gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./food-app/dist
        publish_branch: gh-pages
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Deploy to GitHub Pages from dev branch'